name: dev
on:
    workflow_dispatch:
    push:
        branches:
            - dev
            - releases/**
jobs:
    dev:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            NEXT_PUBLIC_PICANTE_API_END_POINT: ${{ secrets.NEXT_PUBLIC_PICANTE_API_END_POINT_DEV }}
            NEXT_PUBLIC_PAGE_TITLE_SUFFEX: ${{ secrets.NEXT_PUBLIC_PAGE_TITLE_SUFFEX }}
            NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS }}
            NEXT_PUBLIC_DEX_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_DEX_CONTRACT_ADDRESS }}
            NEXT_PUBLIC_POLYGON_WEBSOCKET: ${{ secrets.NEXT_PUBLIC_POLYGON_WEBSOCKET_TESTNET }}
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v2

            - name: Build Code
              uses: actions/setup-node@v2
              with:
                  node-version: 17

            - name: Install Dependencies
              working-directory: ./
              run: npm install

            - name: Build Project
              working-directory: .
              run: npm run build

            - name: Export Project
              working-directory: ./
              run: npm run export

            - name: Copy to Parent
              run: cp -a ./out build

            - name: Deploy
              uses: reggionick/s3-deploy@v3
              with:
                  folder: build
                  bucket: ${{ secrets.S3_BUCKET_DEV }}
                  bucket-region: ${{ secrets.S3_BUCKET_REGION }}
                  dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
                  invalidation: /
                  delete-removed: true
                  no-cache: true
                  private: true
