name: prod
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  prod:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Version Checkup
        working-directory: ./
        run: |
          echo "GITHUB_REF $GITHUB_REF"
          echo "GITHUB_SHA $GITHUB_SHA"

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NEXT_PUBLIC_PAGE_TITLE_SUFFEX: ${{ secrets.NEXT_PUBLIC_PAGE_TITLE_SUFFEX }}
          envkey_NEXT_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_URL }}
          envkey_NEXT_PUBLIC_PICANTE_API_HOST: ${{ secrets.NEXT_PUBLIC_PICANTE_API_END_POINT }}
          envkey_NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS_STAGE }}
          envkey_NEXT_PUBLIC_DEX_CONTRACT_ADDRESS: ${{ secrets.NEXT_PUBLIC_DEX_CONTRACT_ADDRESS_STAGE }}
          envkey_NEXT_PUBLIC_POLYGON_WEBSOCKET: ${{ secrets.NEXT_PUBLIC_POLYGON_WEBSOCKET_TESTNET }}
          envkey_NEXT_PUBLIC_NETWORK_BASE_URL: ${{ secrets.NEXT_PUBLIC_NETWORK_BASE_URL_DEV }}
          envkey_NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          envkey_NEXT_PUBLIC_HOTJAR_ID: ${{ secrets.NEXT_PUBLIC_HOTJAR_ID }}
          envkey_NEXT_PUBLIC_HOTJAR_SV: ${{ secrets.NEXT_PUBLIC_HOTJAR_SV }}
          file_name: .env
          fail_on_empty: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: picante-web-prod-erc
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and redeploy
        uses: jaroldwong/ecr-push-and-ecs-deploy@v1.1
        with:
          ecr-registry: ${{ steps.login-ecr.outputs.registry }}
          ecr-repository: 'picante-web-prod-erc'
          ecs-cluster: 'picante-web-ecs-prod'
          ecs-service: 'picante-web-prod-task_definition'
